project:
  type: book
  output-dir: docs

book:
  title: "POV: Descubres lo que dicen tus genes"
  site-url: https://github.com/EveliaCoss/CdeCMx2026_Club_LPZ3_libro
  page-footer:  "POV: Descubres lo que dicen tus genes - Clubes de Ciencia México" 
  sidebar: 
    # background: "#ffcccc"
    logo: "flyer/logo_cdecmx.png" # Logo ENES
    search: true
  author: 
    - name: Evelia Coss
      degrees: PhD
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      github: https://github.com/zurielceja
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: México
          url: https://www.enesjuriquilla.unam.mx/
    - name: Zuriel Ceja
      degrees: PhD student
      url: https://www.qimrb.edu.au/about/our-people/zuriel-ceja-de-la-cruz
      orcid: https://orcid.org/0000-0003-2392-1964
      email: Zuriel.ceja@qimrberghofer.edu.au
      affiliations:
        - name: QIMR Berghofer / The University of Queensland 
          country: Australia
          url: https://www.qimrb.edu.au/        
  # date: "6/15/2026"
  page-navigation: true
  chapters:
    - index.qmd          # Información general
    - Presentaciones.qmd # Bienvenida: Tú y tus genes    
    - part: "**Pre-requisitos**"
      chapters: 
      - install_R.qmd # Instalación de R y RStudio    
    - part: "**Sección 1** - Introducción: Datos, Genes, y Tú"
      chapters:  
      - Introduccion.qmd   # Descubre qué son los genes
      - Parte1.qmd         # Buenas practicas    
    - part: "**Sección 2** - Introducción a R y RStudio"
      chapters:  
      - Parte2.qmd # introducción a R
      - Parte3.qmd # Estructura de datos en R
      - Parte4.qmd  # Manipulación de datos
      - Act1_seccion2.qmd # Actividad: Manos a la obtra 
    - part: "**Sección 3** - Estructura del proyecto final"
      chapters: 
      - Act2_seccion3.qmd # Actividad: Lo que los datos nos cuentan
      - Explicacion_ProyectoFinal.qmd # Explicación del proyecto final
      - Explicacion_Poster.qmd # Cómo comunicar ciencia en un póster    
    - part: "**Sección 4** - Gráficos con ggplot2"
      chapters:  
      - Parte5.qmd # Intro a ggplot
      - Parte6.qmd # La gramatica de los gráficos
      - Parte7.qmd # Básicos de la visualización de datos
      - Parte8.qmd # Construyendo gráficas capa por capa
      - Parte9.qmd # estéticas globales
      - Parte10.qmd # esteticos locales
      - Parte11.qmd # Temas
      - Parte12.qmd # facetas
      - Parte13.qmd # Geometrías
      - Parte14.qmd # Ejercicios finales
      - Act3_seccion4.qmd # Actividad:
    - part: "**Sección 5** - Descubre patrones en los datos"
      chapters: 
      - Parte15.qmd # Identificación de patrones en conjuntos de datos reales
      - Parte16.qmd # Actividad: descubre algo interesante en un conjunto de datos
      - Act4_seccion5.qmd # Actividad: descubre algo interesante en un conjunto de datos
    - part: "**Sección 6** - Datos biológicos"
      chapters: 
      - Parte17.qmd # Primer vistazo a datos biológicos 
      - Parte18.qmd # Creación de tablas con información con estadística descriptiva
      - Act5_seccion6.qmd # Actividad: Casos de estudio salud pública
    - part: "**Sección 7** - Caso de estudio: Genes y el sistema inmune"
      chapters: 
      - Parte19.qmd # Variantes genéticas y enfermedades del sistema inmune
      - Parte20.qmd # Exploración de bases de datos públicas
      - Act6_seccion7.qmd # Actividad: Explora datos genéticos reales
    - part: "**Sección 8** - Preguntas biológicas y reportes en Quarto"
      chapters: 
      - Parte21.qmd # Cómo formular preguntas biológicas
      - Act7_seccion8.qmd # Actividad: de la pregunta al análisis
      - Parte22.qmd # Creación de reportes con Quarto
      - Act8_seccion8.qmd # Actividad en equipo: identificación de patrones en datos genéticos
    - part: "**Sección 9** - Cerebro, Conducta y ambiente (Gene × Environment)"
      chapters: 
      - Parte23.qmd # Salida de campo: ecosistemas de La Paz
      - Parte24.qmd # ¿Cómo influyen las variantes genéticas en nuestro riesgo de salud?
      - Parte25.qmd # ¿Qué significa tener una predisposición genética?
      - Parte26.qmd # Introducción a la salud mental y a los datos relacionados con el cerebro
      - Parte27.qmd # Estrés, sueño y hábitos: la interacción gene × entorno
      - Act9_seccion9.qmd # Actividad en equipo: continuación del póster 
    - part: "**Sección 10** - Recta final del proyecto"
      chapters: 
      - Parte28.qmd # Análisis y visualización de tus datos
      - Parte29.qmd # Creación de paneles de figuras
     
      
  # Information
  repo-url: https://github.com/EveliaCoss/CdeCMx2026_Club_LPZ3_libro # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "flyer/logo_cdecmx.png" # icono de la pagina en pestana


format:
  html:
    toc-depth: 4
    number-depth: 3
    # css
    css: styles.css
    linkcolor: "#007f99"
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      # dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-annotations: hover #c(hover, below, select): posicion https://quarto.org/docs/authoring/code-annotation.html
    code-block-bg: true # Bloque de código
    code-block-border-left: "#007f99" # color del borde izquierdo del codigo
    syntax-highlighting: arrow # Estilo de los codigos https://quarto.org/docs/output-formats/html-code.html#highlighting
    freeze: false  # Desactivar congelamiento

editor: visual

lang: es

