project:
  type: book
  output-dir: docs

book:
  title: "POV: Descubres lo que dicen tus genes"
  site-url: https://github.com/EveliaCoss/CdeCMx2026_Club_LPZ3_libro
  page-footer:  "POV: Descubres lo que dicen tus genes - Clubes de Ciencia México" 
  sidebar: 
    # background: "#ffcccc"
    logo: "flyer/logo_cdecmx.png" # Logo ENES
    search: true
  author: 
    - name: Evelia Coss
      degrees: PhD
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      github: https://github.com/zurielceja
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: México
          url: https://www.enesjuriquilla.unam.mx/
    - name: Zuriel Ceja
      degrees: PhD student
      url: https://www.qimrb.edu.au/about/our-people/zuriel-ceja-de-la-cruz
      orcid: https://orcid.org/0000-0003-2392-1964
      email: Zuriel.ceja@qimrberghofer.edu.au
      affiliations:
        - name: QIMR Berghofer / The University of Queensland 
          country: Australia
          url: https://www.qimrb.edu.au/        
  # date: "6/15/2026"
  page-navigation: true
  chapters:
    - index.qmd      # Información general
    - Presentaciones.qmd
    - part: "**Pre-requisitos**"
      chapters: 
      - install_R.qmd # Instalación de R y RStudio
      - Parte1.qmd # Buenas practicas
    - part: "**Sección 1** - Introducción a R y RStudio"
      chapters:  
      - Parte26.qmd
      - Parte27.qmd 
      - Parte28.qmd 
    - part: "**Sección 2** - Gráficos con ggplot2 "
      chapters:  
      - Parte30.qmd # Intro a ggplot
      - Parte31.qmd # La gramatica de los gráficos
      - Parte32.qmd #  Básicos de la visualización de datos
      - Parte33.qmd # Construyendo gráficas capa por capa
      - Parte34.qmd # estéticas globales
      - Parte35.qmd # esteticos locales
      - Parte36.qmd # Temas
      - Parte37.qmd # facetas
      - Parte38.qmd # Geometrías
      - Parte39.qmd # Ejercicios finales

      
  # Information
  repo-url: https://github.com/EveliaCoss/CdeCMx2026_Club_LPZ3_libro # link de Github
  sharing: [twitter, facebook, linkedin]
  # favicon: "rsgMexico.jpeg" # icono de la pagina en pestana


format:
  html:
    toc-depth: 4
    number-depth: 3
    # css
    css: styles.css
    linkcolor: "#007f99"
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      # dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-annotations: hover #c(hover, below, select): posicion https://quarto.org/docs/authoring/code-annotation.html
    code-block-bg: true # Bloque de código
    code-block-border-left: "#007f99" # color del borde izquierdo del codigo
    syntax-highlighting: arrow # Estilo de los codigos https://quarto.org/docs/output-formats/html-code.html#highlighting
    freeze: false  # Desactivar congelamiento

editor: visual

lang: es

