# Repositorios

Un repositorio es donde se va a almacenar toda la información de nuestro proyecto, es donde vamos a tener toda la historia y registro de cambios y usuarios. Es recomendable tener un repositorio por proyecto y no multiples proyectos en un solo repositorio.

Vamos a movernos a la carpeta del curso y vamos a hacer una carpeta para trabajar con git.

``` bash
$ cd Curso_Comp_cient
$ mkdir Mi_primer_repo
$ cd Mi_primer_repo
```

Para inicializar un repositorio usamos lo siguiente (dentro de la carperta).

``` bash
$ git init
```

Al inicializar el repositorio, cualquier carpeta y archivo que se cree dentro de la carpeta quedará su registro, no es necesario inicializar las carpetas anidadas.

Si revisamos que tiene la carpeta solo con `ls` no vamos a notar ningún cambio pero si listamos con la opción `-a` veremos que contiene archivos ocultos. En el archivo `.git` se almacena **TODA** la información de nuestro repositorio, así que si lo borramos perderemos todo el historial del repositorio.

``` bash
$ ls -a
```

Para cambiar manualmente la rama de nuestro repositorio si no es la main, lo podemos hacer como sigue.

``` bash
$ git checkout -b main
```

Para preguntarle a git el estado de nuestro proyecto:

``` bash
$ git status
```

Si dentro de una carpeta preguntamos `git status` y obtenemos el siguiente mensaje:

``` output
fatal: not a git repository (or any of the parent directories): .git
```

significa que si podemos inicializarlo como un repositorio.

:::: callout-note
## Ejercicio 1

Dentro de la carpeta `Mi_primer_repo` crea una carpeta llamada `subproyecto1`. Si quieres llevar un registro de lo que hagas en ese subproyecto: ¿debes inicializarla? Inicializala. Ahora, ¿cómo borras el archivo `.git`?

::: {.callout-tip collapse="true" icon="false"}
## Solución
:::
::::
